version: 0.1.{build}
os: Visual Studio 2015 CTP 6
configuration: Debug
platform: ARM
install:
- cmd: >-
    node --version
    npm --version
    npm install -g cordova
    npm install
build_script:
- cmd: >-
    cordova platforms add windows

    cordova build windows --arch=arm --Debug
    cordova build windows --arch=x64 --Debug
    cordova build windows --arch=x86 --Debug
artifacts:
- path: platforms\windows\**\*.appx